site_name: RoboStack
site_url: https://robostack.github.io/
repo_url: https://github.com/RoboStack/robostack.github.io
edit_uri: edit/master/docs/
nav:
    - Home: index.md
    # - What's New: WhatsNew.md
    - Getting Started: GettingStarted.md
    - Available Packages:
      - ROS1 Noetic: noetic.md
      - ROS2 Foxy: foxy.md
      - ROS2 Galactic: galactic.md
      - ROS2 Humble: humble.md
      - ROS2 Jazzy: jazzy.md
      - JupyterRos: JupyterRos.md
    - Support: support.md
    - Contributing: Contributing.md
    - FAQ: FAQ.md

extra_css: [extra.css]

theme:
  name: material
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - navigation.instant
    - navigation.path

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:      
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

use_directory_urls: false
strict: true
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
plugins:
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true
