site_name: RoboStack
repo_url: https://github.com/RoboStack/robostack.github.io
edit_uri: edit/master/
nav:
    - Home: index.md
    - What's New: WhatsNew.md
    - Getting Started: GettingStarted.md
    - ROS1:
      - Noetic: noetic.md
    - ROS2:
      - Foxy: foxy.md
      - Galactic: galactic.md
        
    - Support:
        - Create an Issue: https://github.com/RoboStack/robostack.github.io
        - Contributing: Contributing.md
theme: material
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.emoji:      
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
use_directory_urls: false
strict: true