site_name: RoboStack
site_url: https://robostack.github.io/
repo_url: https://github.com/RoboStack/robostack.github.io
edit_uri: edit/master/docs/
nav:
    - Home: index.md
    # - What's New: WhatsNew.md
    - Getting Started: GettingStarted.md
    - Available Packages:
      - ROS1 Noetic: noetic.md
      - ROS2 Foxy: foxy.md
      - ROS2 Galactic: galactic.md
    - Support:
      - Create an Issue (docs): https://github.com/RoboStack/robostack.github.io/issues/new
      - Create an Issue (ROS Noetic): https://github.com/RoboStack/ros-noetic/issues/new
      - Create an Issue (ROS2 Foxy): https://github.com/RoboStack/ros-foxy/issues/new
      - Create an Issue (ROS2 Galactic): https://github.com/RoboStack/ros-galactic/issues/new
    - Contributing: Contributing.md

theme: material
markdown_extensions:
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.emoji:      
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
use_directory_urls: false
strict: true
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
plugins:
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true
