name: ci
on:
  push:
    branches:
      - master
      - main
  workflow_run:
    workflows: ["Update distro tables"]
    types: [completed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.3
      - run: pixi run mkdocs gh-deploy --force --no-strict
