name: Copy staging packages

on:
  workflow_dispatch:
  schedule:
    - cron: "42 * * * *"

permissions:
  contents: read

jobs:
  copy-packages-noetic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
      - env:
          ANACONDA_API_TOKEN: ${{ secrets.ROBOSTACK_NOETIC_ANACONDA_API_TOKEN }}
        run: |
          python scripts/copy-to-distro-specific-channel.py noetic 2025-01-01
        shell: pixi run bash -e {0}

  copy-packages-humble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
      - env:
          ANACONDA_API_TOKEN: ${{ secrets.ROBOSTACK_HUMBLE_ANACONDA_API_TOKEN }}
        run: |
          python scripts/copy-to-distro-specific-channel.py humble 2025-01-01
        shell: pixi run bash -e {0}
