name: Copy staging packages

on:
  workflow_dispatch:
  schedule:
    - cron: "42 * * * *"

jobs:
  copy-packages-noetic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.3
      - env:
          ANACONDA_API_TOKEN: ${{ secrets.ROBOSTACK_NOETIC_ANACONDA_API_TOKEN }}
        run: |
          python copy-to-distro-specific-channel.py noetic 2025-01-01
        shell: pixi run bash -e {0}

  copy-packages-humble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.3
      - env:
          ANACONDA_API_TOKEN: ${{ secrets.ROBOSTACK_HUMBLE_ANACONDA_API_TOKEN }}
        run: |
          python copy-to-distro-specific-channel.py humble 2025-01-01
        shell: pixi run bash -e {0}
