name: Copy staging packages

on:
  workflow_dispatch:
  schedule:
    - cron: "42 * * * *"

permissions:
  contents: read

jobs:
  copy-packages-noetic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
      - env:
          ANACONDA_API_TOKEN: ${{ secrets.ROBOSTACK_NOETIC_ANACONDA_API_TOKEN }}
        run: |
          python scripts/copy-to-distro-specific-channel.py noetic 2025-01-01
        shell: pixi run bash -e {0}

  copy-packages-humble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
      - env:
          ANACONDA_API_TOKEN: ${{ secrets.ROBOSTACK_HUMBLE_ANACONDA_API_TOKEN }}
        run: |
          python scripts/copy-to-distro-specific-channel.py humble 2025-01-01
        shell: pixi run bash -e {0}
