name: Update noetic table

on:
  push:
  pull_request:
  schedule:    
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install pyyaml requests rich
    - name: Checkout ros-noetic
      uses: actions/checkout@v2
      with:
        repository: RoboStack/ros-noetic
    - name: Create table
      run: |
        python utils/compare_pkg_completeness.py
    - name: Rename file
      run: |
       mv version_compare.html noetic.html 
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add noetic.html
        git commit -m "Update table"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
