name: Update distro tables

on:
  schedule:    
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install pyyaml requests
    - name: Checkout robostack.github.io
      uses: actions/checkout@v2
    - name: Create table noetic
      run: |
        python utils/compare_pkg_completeness.py noetic robostack-staging
    - name: Create table foxy
      run: |
        python utils/compare_pkg_completeness.py foxy robostack
    - name: Create table galactic
      run: |
        python utils/compare_pkg_completeness.py galactic robostack-experimental
    - name: Create table humble
      run: |
        python utils/compare_pkg_completeness.py humble robostack-staging
    - name: Commit changes
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/noetic.md
        git add docs/foxy.md
        git add docs/galactic.md
        git add docs/humble.md
        git commit -m "Update tables"
      continue-on-error: true
    - name: Push changes
      if: steps.commit.outcome == 'success'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
