name: Upgrade dependencies

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    # At 05:00 on day 1 of the month
    - cron: 0 5 1 * *

jobs:
  pixi-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          run-install: false
      - name: Upgrade dependencies
        run: |
          set -o pipefail
          pixi upgrade --json | pixi exec pixi-diff-to-markdown >> diff.md
      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: upgrade pixi dependencies"
          title: Upgrade pixi dependencies
          body-path: diff.md
          branch: upgrade-pixi
          base: main
          labels: pixi
          delete-branch: true
          add-paths: |
            pixi.toml
            pixi.lock
